name: Build and Publish image to Docker Hub
on: 
  [workflow_dispatch]
jobs:
  publish-images:
    runs-on: ubuntu-lates
    steps:
      - name: checkout
        uses: actions:checkout@v4
      - name: Build Image
        run: docker build ./api -t 2808/devops-qr-code-api:latest
      - name: push image todocker hub
        run: |
          docker push 2808/devops-qr-code-api:latest