name: Build and Publish image to Docker Hub
on: 
  [workflow_dispatch]
jobs:
  publish-images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build Image
        run: |
          docker build ./api/ -t 2808/devops-qr-code-api:latest
          docker build ./front-end-nextjs/ -t 2808/devops-qr-code-frontend:latest
      - name: push image to docker hub
        run: |
          docker login -u 2808 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push 2808/devops-qr-code-api:latest
          docker push 2808/devops-qr-code-frontend:latest